# Uncomment the following lines to define your default indexer and rpc urls
indexer_url = "https://index2-namada.5elementsnodes.com"
rpc_url = "https://rpc-namada.5elementsnodes.com"
masp_indexer_url = "https://masp2-namada.5elementsnodes.com"
#localnet_enabled = false
#fathom_site_id = ""
